#!/bin/bash
HOME_PATH="/home/strawberry/Downloads/WIDzard"
rm -rf $HOME_PATH/RELEASE_Boeffla
rm -rf $HOME_PATH/RELEASE_Wolfson
cp -ax /home/strawberry/Downloads/WIDzard/Zip $HOME_PATH/RELEASE_Boeffla
cp -ax /home/strawberry/Downloads/WIDzard/Zip $HOME_PATH/RELEASE_Wolfson
echo "###########################################################"
echo 
echo "[BOEFFLA_SKT]"
echo
echo "###########################################################"
./Boeffla_SKT
echo "###########################################################"
echo 
echo "[BOEFFLA_KT]"
echo
echo "###########################################################"
./Boeffla_KT
echo "###########################################################"
echo 
echo "[BOEFFLA_LG]"
echo
echo "###########################################################"
./Boeffla_LG
echo "###########################################################"
echo 
echo "[WOLFSON_SKT]"
echo
echo "###########################################################"
./Wolfson_SKT
echo "###########################################################"
echo 
echo "[WOLFSON_KT]"
echo
echo "###########################################################"
./Wolfson_KT
echo "###########################################################"
echo 
echo "[WOLFSON_LG]"
echo
echo "###########################################################"
./Wolfson_LG
echo "###########################################################"
echo 
echo "                                   		  Make ZIP File"
echo
echo "###########################################################"
cd $HOME_PATH/RELEASE_Boeffla
zip -0 -r Boeffla_ALL_`date +"%Y-%m-%d-%H-%M-%S"` *
ls -al $HOME_PATH/RELEASE
cd $HOME_PATH/RELEASE_Wolfson
zip -0 -r Wolfson_ALL_`date +"%Y-%m-%d-%H-%M-%S"` *
echo "Done"
exit
