#!/bin/bash
HOME_PATH="/home/strawberry/Downloads/WIDzard"
rm -rf $HOME_PATH/RELEASE
cp -ax /home/strawberry/Downloads/WIDzard/Zip $HOME_PATH/RELEASE
echo "###########################################################"
echo 
echo "                                          Build SKT Kernel"
echo
echo "###########################################################"
./Wolfson_SKT
echo "###########################################################"
echo 
echo "                                           Build KT Kernel"
echo
echo "###########################################################"
./Wolfson_KT
echo "###########################################################"
echo 
echo "                                           Build LG Kernel"
echo
echo "###########################################################"
./Wolfson_LG
echo "###########################################################"
echo 
echo "                                   		  Make ZIP File"
echo
echo "###########################################################"
cd $HOME_PATH/RELEASE
zip -0 -r Wolfson_ALL_`date +"%Y-%m-%d-%H-%M-%S"` *
ls -al $HOME_PATH/RELEASE
echo "Done"
exit
