#!/bin/bash
NUM=31;
while [ : ];
do
echo "This NUM = "$NUM;
echo "======================================================="
echo
echo "patch -p1 < ./patch-3.0."$NUM"-"$(($NUM+1))""
echo "======================================================="
patch -p1 < ./patch-3.0."$NUM"-"$(($NUM+1))";
NUM=$(($NUM+1));
done
exit
